# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  RacingGame_config = debug

else ifeq ($(config),release)
  RacingGame_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := RacingGame

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

RacingGame:
ifneq (,$(RacingGame_config))
	@echo "==== Building RacingGame ($(RacingGame_config)) ===="
	@${MAKE} --no-print-directory -C . -f RacingGame.make config=$(RacingGame_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f RacingGame.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   RacingGame"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"